export type ParaphraseMode =
  | "standard"
  | "fluency"
  | "humanize"
  | "formal"
  | "academic"
  | "simple"
  | "creative"
  | "expand"
  | "shorten";

export interface ParaphraseParams {
  intensity: number;       // 0–1: how aggressively to rewrite
  creativity: number;      // 0–1: vocabulary diversity
  naturalness: number;     // 0–1: conversational feel
  complexity: number;      // 0–1: sentence complexity
}

const MODE_DESCRIPTIONS: Record<ParaphraseMode, string> = {
  standard:  "Rewrite naturally, maintaining original meaning while sounding human.",
  fluency:   "Rewrite for smooth, flowing prose with excellent readability.",
  humanize:  "Rewrite to sound authentically human — with natural imperfections, varied rhythm, and genuine voice.",
  formal:    "Rewrite in formal, professional language suitable for business or official contexts.",
  academic:  "Rewrite in scholarly academic style with appropriate terminology and structure.",
  simple:    "Rewrite in clear, simple language that anyone can understand.",
  creative:  "Rewrite with creative flair, vivid language, and engaging narrative voice.",
  expand:    "Rewrite with additional context, explanation, and elaboration to expand the content.",
  shorten:   "Rewrite as a concise summary, cutting unnecessary words while keeping core meaning.",
};

export function buildParaphrasePrompt(
  text: string,
  mode: ParaphraseMode,
  params: ParaphraseParams
): string {
  const intensityLabel = params.intensity > 0.7 ? "aggressively" : params.intensity > 0.4 ? "moderately" : "lightly";
  const creativityLabel = params.creativity > 0.7 ? "rich and diverse" : params.creativity > 0.4 ? "varied" : "straightforward";
  const naturalnessLabel = params.naturalness > 0.7 ? "very conversational and human" : params.naturalness > 0.4 ? "natural" : "neutral";

  return `You are an expert human writer. Your task is to rewrite the following text in "${mode}" mode.

Mode: ${MODE_DESCRIPTIONS[mode]}

Rewriting parameters:
- Intensity: ${intensityLabel} (${Math.round(params.intensity * 100)}%)  — how much to change the original
- Creativity: ${creativityLabel} vocabulary (${Math.round(params.creativity * 100)}%)
- Naturalness: ${naturalnessLabel} tone (${Math.round(params.naturalness * 100)}%)
- Complexity: ${Math.round(params.complexity * 100)}% sentence complexity

Critical rules to avoid AI detection:
1. Vary sentence lengths naturally — mix short punchy sentences with longer flowing ones
2. Use contractions where natural (don't, it's, you're, we've)
3. Avoid patterns typical of AI: starting too many sentences with "The", "This", "It is", "Furthermore", "Additionally", "In conclusion"
4. Add subtle transitional phrases that feel organic
5. Occasionally use em dashes, parenthetical asides, or rhetorical questions
6. Avoid repetitive sentence structures back-to-back
7. Do NOT add any introductory text like "Here's the rewritten version:" — output ONLY the rewritten text

Input text:
"""
${text}
"""

Rewritten text:`;
}

export function buildDetectionPrompt(text: string): string {
  return `You are an expert AI content detector. Analyze the following text and estimate the probability that it was generated by an AI (like GPT-4, Claude, Gemini, etc.).

Look for these AI writing patterns:
- Overly uniform sentence structure
- Excessive use of transitional phrases (Furthermore, Additionally, In conclusion, etc.)
- Lack of genuine personal voice or perspective
- Perfect grammar with no natural imperfections
- Predictable paragraph structure
- Hedging language (it's important to note, it should be mentioned, etc.)
- Repetitive sentence starters
- Absence of contractions in informal contexts
- Generic, safe language without strong opinions

Analyze the text and respond with a JSON object ONLY (no markdown, no explanation):
{
  "aiScore": <number 0-100, where 100 = definitely AI>,
  "humanScore": <number 0-100, where 100 = definitely human>,
  "confidence": <"low"|"medium"|"high">,
  "detectedPatterns": [<list of up to 5 specific AI patterns found, or empty array if human>],
  "verdict": <"AI-Generated"|"Likely AI"|"Mixed"|"Likely Human"|"Human-Written">
}

Text to analyze:
"""
${text}
"""`;
}
